theme: jekyll-theme-chirpy

url:
baseurl:

lang: en #id-ID
timezone: Asia/Tokyo

title: Andre Attamimi
tagline: Software Developer
description: >-
  Four freedoms, exploring and collaborating continuously
avatar: https://github.com/sionta.png?size=100

img_cdn:
theme_mode: # [light | dark]

github:
  username: sionta
twitter:
  username: R007MMXV
social:
  name: Andre Attamimi
  email: andreattamimi@outlook.co.id
  links:
    - https://twitter.com/R007MMXV
    - https://github.com/sionta
    - https://www.linkedin.com/in/andreattamimi
    # - https://www.facebook.com/username

google_site_verification: B5hQgjOCQikiEQoYbXisgVnKUPmpUg13FUz
google_analytics:
  id: G-5EKDX8MEPB
google_adsense:
  id: pub-6055274552295504

comments:
  active: giscus
  giscus:
    repo: sionta/sionta
    repo_id: R_kgDOKByokw
    category: Q&A
    category_id: DIC_kwDOKByok84Cd8WP
    mapping:
    input_position:
    lang:
    reactions_enabled: 1

toc: true
paginate: 10

assets:
  self_host:
    enabled: true
    env: # [development | production]

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

sass:
  style: compressed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  portfolio:
    output: true
    sort_by: order
  legals:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true
  - scope:
      path: ""
      type: legals
    values:
      layout: page
      permalink: /:title
  - scope:
      path: ""
      type: portfolio
    values:
      layout: page
      permalink: /:title

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

exclude:
  - "*.bak"
  - "*.gem"
  - "*.gemspec"
  - "/assets/excludes"
  - "/tools"
  - "LICENSE"
  - "package*.json"
  - "README.md"
  - "rollup.config.js"
