name: fork sync

on:
  schedule:
    - cron: '0 1 * * 1' # Runs at 01:00 on Mondays.
  workflow_dispatch:

jobs:
  fork-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: pwsh
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $excludes = "sionta/mixplorer", "sionta/imageglass"
          & ./tools/fork-sync.ps1 -e $excludes
